# Form implementation generated from reading ui file '.\lib\ui\PackageManagerWidget.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class PackageManagerWidget(QtWidgets.QWidget):
    def __init__(self, application):
        super().__init__()
        self.application = application
        self.setupUi()

    def setupUi(self):
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.PackageManagerSplitter = QtWidgets.QSplitter(self)
        self.PackageManagerSplitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.PackageManagerSplitter.setObjectName("PackageManagerSplitter")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.PackageManagerSplitter)
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.SearchPackageLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.SearchPackageLineEdit.setToolTipDuration(1)
        self.SearchPackageLineEdit.setObjectName("SearchPackageLineEdit")
        self.horizontalLayout_4.addWidget(self.SearchPackageLineEdit)
        self.FindPackageButton = QtWidgets.QToolButton(self.verticalLayoutWidget_5)
        self.FindPackageButton.setObjectName("FindPackageButton")
        self.horizontalLayout_4.addWidget(self.FindPackageButton)
        self.AddPackageButton = QtWidgets.QToolButton(self.verticalLayoutWidget_5)
        self.AddPackageButton.setObjectName("AddPackageButton")
        self.horizontalLayout_4.addWidget(self.AddPackageButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.PackageViewTreeView = QtWidgets.QTreeView(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PackageViewTreeView.sizePolicy().hasHeightForWidth())
        self.PackageViewTreeView.setSizePolicy(sizePolicy)
        self.PackageViewTreeView.setAlternatingRowColors(True)
        self.PackageViewTreeView.setWordWrap(True)
        self.PackageViewTreeView.setObjectName("PackageViewTreeView")
        self.PackageViewTreeView.header().setDefaultSectionSize(39)
        self.verticalLayout_5.addWidget(self.PackageViewTreeView)
        self.PackageManagerTabWidget = QtWidgets.QTabWidget(self.PackageManagerSplitter)
        self.PackageManagerTabWidget.setTabsClosable(False)
        self.PackageManagerTabWidget.setMovable(True)
        self.PackageManagerTabWidget.setObjectName("PackageManagerTabWidget")
        self.gridLayout.addWidget(self.PackageManagerSplitter, 0, 0, 1, 1)

        self.retranslateUi(self)
        self.PackageManagerTabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.SearchPackageLineEdit.setToolTip(_translate("Form", "Search Transport Package"))
        self.SearchPackageLineEdit.setPlaceholderText(_translate("Form", "Search Transport Package"))
        self.FindPackageButton.setText(_translate("Form", "Find"))
        self.AddPackageButton.setText(_translate("Form", "Add"))
