# Form implementation generated from reading ui file '.\lib\ui\SessionDetailsDialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class SessionDetailsDialog(QtWidgets.QDialog):

    def __init__(self, application):
        super(SessionDetailsDialog, self).__init__(flags=QtCore.Qt.WindowType.Dialog, parent=application)

        self.resize(440, 226)
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self)
        self.label_5.setMinimumSize(QtCore.QSize(120, 0))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(self)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.ServerAddress = QtWidgets.QLineEdit(self)
        self.ServerAddress.setObjectName("ServerAddress")
        self.gridLayout.addWidget(self.ServerAddress, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.UserName = QtWidgets.QLineEdit(self)
        self.UserName.setObjectName("UserName")
        self.gridLayout.addWidget(self.UserName, 3, 2, 1, 1)
        self.UserPassword = QtWidgets.QLineEdit(self)
        self.UserPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.UserPassword.setObjectName("UserPassword")
        self.gridLayout.addWidget(self.UserPassword, 4, 2, 1, 1)
        self.SessionName = QtWidgets.QLineEdit(self)
        self.SessionName.setObjectName("SessionName")
        self.gridLayout.addWidget(self.SessionName, 0, 2, 1, 1)
        self.DatabaseName = QtWidgets.QLineEdit(self)
        self.DatabaseName.setObjectName("DatabaseName")
        self.gridLayout.addWidget(self.DatabaseName, 2, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 6, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 2, 1, 1)

        self.setTabOrder(self.SessionName, self.ServerAddress)
        self.setTabOrder(self.ServerAddress, self.DatabaseName)
        self.setTabOrder(self.DatabaseName, self.UserName)
        self.setTabOrder(self.UserName, self.UserPassword)

        self.retranslateUi(self)
        self.buttonBox.accepted.connect(self.accept)
        self.buttonBox.rejected.connect(self.reject)
        QtCore.QMetaObject.connectSlotsByName(self)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Session Details"))
        self.label_5.setText(_translate("Dialog", "User Password"))
        self.label_2.setText(_translate("Dialog", "Server Address"))
        self.label.setText(_translate("Dialog", "Session Name"))
        self.label_4.setText(_translate("Dialog", "User Name"))
        self.label_3.setText(_translate("Dialog", "Database Name"))

    @property 
    def session_name(self):
        return self.SessionName.text()

    @property 
    def server_address(self):
        return self.ServerAddress.text()

    @property 
    def database_name(self):
        return self.DatabaseName.text()

    @property 
    def user_name(self):
        return self.UserName.text()

    @property 
    def user_password(self):
        return self.UserPassword.text()

    @property
    def form_values(self):
        values = {
            "session_name": self.session_name,
            "server_address": self.server_address,
            "database_name": self.database_name,
            "user_name":self.user_name, 
            "user_password": self.user_password
            }
        return values
        