on:
  workflow_dispatch:

jobs:
  build_win:
    name: Build windows app
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3

      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: 3.14
          # Used to specify the packages to install with pip after setting up Python. 
          pip-install: -r requirements.txt
          
